name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Check repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build pandoc pandoc-citeproc texlive-latex-recommended texlive-pictures texlive-latex-extra librsvg2-bin latexmk
      - name: Generate slides
        run: |
          # I don't know why, but pandoc doesn't build using make. I have to use Ninja...
          cmake -Bbuild -Hslides -G "Ninja"
          cmake --build build
          mkdir materials/
          cp build/output/beamer/* materials/
          zip -r materials.zip materials/
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            materials.zip
